=== zboszor/OpenCReports/opencreport.dtd
<!ELEMENT OpenCReport (Paths?,Datasources?,Queries?,(Part|Report)*)>
<!ATTLIST OpenCReport
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	precision_bits CDATA #IMPLIED
	rounding_mode (nearest|to_minus_inf|to_inf|to_zero|away_from_zero|faithful) "nearest"
	locale CDATA #IMPLIED
	translation_domain CDATA #IMPLIED
	translation_directory CDATA #IMPLIED >
<!ELEMENT Paths (Path+)>
<!ELEMENT Path EMPTY>
<!ATTLIST Path
    value CDATA #REQUIRED>
<!ELEMENT Datasources (Datasource+)>
<!ELEMENT Datasource EMPTY>
<!ATTLIST Datasource
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	encoding CDATA #IMPLIED
	host CDATA #IMPLIED
	unix_socket CDATA #IMPLIED
	port CDATA #IMPLIED
	dbname CDATA #IMPLIED
	user CDATA #IMPLIED
	password CDATA #IMPLIED
	connstr CDATA #IMPLIED
	optionfile CDATA #IMPLIED
	group CDATA #IMPLIED
	filename CDATA #IMPLIED >
<!ELEMENT Queries (Query)+>
<!ELEMENT Query (#PCDATA)>
<!ATTLIST Query
	name CDATA #REQUIRED
	datasource CDATA #REQUIRED
	value CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	coltypes CDATA #IMPLIED
	follower_for CDATA #IMPLIED
	follower_expr CDATA #IMPLIED >
<!ELEMENT Part (PageHeader|PageFooter|ReportHeader|ReportFooter|pr)*>
<!ATTLIST Part
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	orientation CDATA #IMPLIED
	topMargin CDATA #IMPLIED
	top_margin CDATA #IMPLIED
	bottomMargin CDATA #IMPLIED
	bottom_margin CDATA #IMPLIED
	leftMargin CDATA #IMPLIED
	left_margin CDATA #IMPLIED
	rightMargin CDATA #IMPLIED
	right_margin CDATA #IMPLIED
	paperType CDATA #IMPLIED
	paper_type CDATA #IMPLIED
	iterations CDATA #IMPLIED
	suppressPageHeaderFirstPage CDATA #IMPLIED >
<!ELEMENT pr (pd)+>
<!ATTLIST pr
	layout CDATA #IMPLIED
	newpage CDATA #IMPLIED >
<!ELEMENT pd (Report|load)*>
<!ATTLIST pd
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	border_width CDATA #IMPLIED
	border_color CDATA #IMPLIED
	detail_columns CDATA #IMPLIED
	column_pad CDATA #IMPLIED
	suppress CDATA #IMPLIED >
<!ELEMENT load EMPTY>
<!ATTLIST load
	name CDATA #IMPLIED
	query CDATA #IMPLIED
	iterations CDATA #IMPLIED >
<!ELEMENT Report ((Alternate|NoData)|(Breaks?,Variables?)|PageHeader|PageFooter|ReportHeader|ReportFooter|(Detail|Graph|Chart)*|xi:include)* >
<!ATTLIST Report
	pagesAcross CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	orientation CDATA #IMPLIED
	topMargin CDATA #IMPLIED
	top_margin CDATA #IMPLIED
	bottomMargin CDATA #IMPLIED
	bottom_margin CDATA #IMPLIED
	leftMargin CDATA #IMPLIED
	left_margin CDATA #IMPLIED
	rightMargin CDATA #IMPLIED
	right_margin CDATA #IMPLIED
	paperType CDATA #IMPLIED
	paper_type CDATA #IMPLIED
	iterations CDATA #IMPLIED
	suppress CDATA #IMPLIED
	suppressPageHeaderFirstPage CDATA #IMPLIED
	query CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	field_header_priority CDATA #IMPLIED
	detail_columns CDATA #IMPLIED
	column_pad CDATA #IMPLIED >
<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
	href CDATA #REQUIRED >
<!ELEMENT Alternate (NoData) >
<!ELEMENT NoData (Output) >
<!ELEMENT ReportHeader (Output)* >
<!ELEMENT PageHeader (Output)* >
<!ELEMENT ReportFooter (Output)* >
<!ELEMENT PageFooter (Output)* >
<!ELEMENT Output (Line | GeneratedLine | HorizontalLine | Image | Barcode | ImageEnd)* >
<!ATTLIST Output
    suppress CDATA #IMPLIED >
<!ELEMENT Line (field | literal | Image | Barcode)* >
<!ATTLIST Line
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	suppress CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT field (#PCDATA) >
<!ATTLIST field
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	format CDATA #IMPLIED
	width CDATA #IMPLIED
	align CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	link CDATA #IMPLIED
	memo CDATA #IMPLIED
	memo_hyphenate CDATA #IMPLIED
	memo_wrap_chars CDATA #IMPLIED
	memo_max_lines CDATA #IMPLIED
	translate CDATA #IMPLIED
	col CDATA #IMPLIED >
<!ELEMENT literal (#PCDATA) >
<!ATTLIST literal
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	format CDATA #IMPLIED
	width CDATA #IMPLIED
	align CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	link CDATA #IMPLIED
	memo CDATA #IMPLIED
	memo_hyphenate CDATA #IMPLIED
	memo_wrap_chars CDATA #IMPLIED
	memo_max_lines CDATA #IMPLIED
	translate CDATA #IMPLIED
	col CDATA #IMPLIED >
<!ELEMENT HorizontalLine EMPTY>
<!ATTLIST HorizontalLine
	size CDATA #IMPLIED
	align CDATA #IMPLIED
	indent CDATA #IMPLIED
	length CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	suppress CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT Image EMPTY >
<!ATTLIST Image
	value CDATA #REQUIRED
	suppress CDATA #IMPLIED
	type CDATA #REQUIRED
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	align CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	text_width CDATA #REQUIRED
	textWidth CDATA #REQUIRED >
<!ATTLIST Barcode
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	suppress CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	type CDATA #IMPLIED
	width CDATA #REQUIRED
	height CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT GeneratedLine EMPTY>
<!ATTLIST GeneratedLine
	element_type CDATA #REQUIRED
	line_font_name CDATA #IMPLIED
	line_font_size CDATA #IMPLIED
	line_bold CDATA #IMPLIED
	line_italic CDATA #IMPLIED
	line_italics CDATA #IMPLIED
	line_suppress CDATA #IMPLIED
	line_color CDATA #IMPLIED
	line_colour CDATA #IMPLIED
	line_bgcolor CDATA #IMPLIED
	line_bgcolour CDATA #IMPLIED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	align CDATA #IMPLIED
	alignment CDATA #IMPLIED
	color CDATA #IMPLIED
	colour CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	bgcolour CDATA #IMPLIED
	font_name CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	format CDATA #IMPLIED
	link CDATA #IMPLIED
	translate CDATA #IMPLIED
	memo CDATA #IMPLIED
	hyphenate CDATA #IMPLIED
	wrap_chars CDATA #IMPLIED
	max_lines CDATA #IMPLIED
	imgtype CDATA #IMPLIED
	text_width CDATA #IMPLIED
	bctype CDATA #IMPLIED >
<!ELEMENT Detail ((FieldHeader|FieldHeaders)?, (FieldDetail|FieldDetails)?, (FieldFooter|FieldFooters)?) >
<!ELEMENT FieldHeader (Output)* >
<!ELEMENT FieldHeaders (Output)* >
<!ELEMENT FieldDetail (Output)* >
<!ATTLIST FieldDetail
	matched CDATA #IMPLIED
	overlay CDATA #IMPLIED >
<!ELEMENT FieldDetails (Output)* >
<!ATTLIST FieldDetails
	matched CDATA #IMPLIED
	overlay CDATA #IMPLIED >
<!ELEMENT FieldFooter (Output)* >
<!ELEMENT FieldFooters (Output)* >
<!ELEMENT Graph (Plot+) >
<!ATTLIST Graph
	name CDATA #IMPLIED
	type CDATA #REQUIRED
	subtype CDATA #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	bold_titles CDATA #IMPLIED
	title CDATA #IMPLIED
	legend_bg_color CDATA #IMPLIED
	legend_orientation CDATA #IMPLIED
	draw_x_line CDATA #IMPLIED
	draw_y_line CDATA #IMPLIED
	grid_color CDATA #IMPLIED
	x_axis_title CDATA #IMPLIED
	y_axis_title CDATA #IMPLIED
	y_axis_mod CDATA #IMPLIED
	y_axis_title_right CDATA #IMPLIED
	y_axis_decimals CDATA #IMPLIED
	y_axis_decimals_right CDATA #IMPLIED >
<!ELEMENT Plot EMPTY>
<!ATTLIST Plot
	axis CDATA #IMPLIED
	field CDATA #IMPLIED
	label CDATA #IMPLIED
	side CDATA #IMPLIED
	disabled CDATA #IMPLIED
	color CDATA #IMPLIED >
<!ELEMENT Chart (HeaderRow?,Row?)>
<!ATTLIST Chart
	name CDATA #IMPLIED
	title CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	cell_width CDATA #IMPLIED
	cell_height CDATA #IMPLIED
	cell_width_padding CDATA #IMPLIED
	cell_height_padding CDATA #IMPLIED
	label_width CDATA #IMPLIED
	header_row CDATA #IMPLIED >
<!ELEMENT HeaderRow EMPTY>
<!ATTLIST HeaderRow
	query CDATA #IMPLIED
	field CDATA #IMPLIED
	colspan CDATA #IMPLIED >
<!ELEMENT Row EMPTY>
<!ATTLIST Row
	row CDATA #IMPLIED
	bar_start CDATA #IMPLIED
	bar_end CDATA #IMPLIED
	label CDATA #IMPLIED
	bar_label CDATA #IMPLIED
	bar_color CDATA #IMPLIED
	bar_label_color CDATA #IMPLIED >
<!ELEMENT Breaks (Break)* >
<!ELEMENT Break (BreakHeader | BreakFooter | BreakFields)* >
<!ATTLIST Break
	name CDATA #REQUIRED
	headernewpage CDATA #IMPLIED
	suppressblank CDATA #IMPLIED
	newpage CDATA #IMPLIED >
<!ELEMENT BreakHeader (Output)* >
<!ELEMENT BreakFooter (Output)* >
<!ELEMENT BreakFields (BreakField)* >
<!ELEMENT BreakField EMPTY>
<!ATTLIST BreakField
	value CDATA #REQUIRED >
<!ELEMENT Variables (Variable)* >
<!ELEMENT Variable EMPTY >
<!ATTLIST Variable
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	baseexpr CDATA #IMPLIED
	intermedexpr CDATA #IMPLIED
	intermed2expr CDATA #IMPLIED
	resultexpr CDATA #IMPLIED
	type (expression|count|sum|average|lowest|highest|custom) "sum"
	basetype (number|string|datetime) "number"
	resetonbreak CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	delayed CDATA #IMPLIED >

=== zboszor/OpenCReports/tests/layout_pdf_xml18_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="5" cols="5" />
		<Query name="b" datasource="myarray" value="'array2'" coltypes="'coltypes'" rows="4" cols="5" />
	</Queries>
	<Part iterations="3">
		<pr>
			<pd>
				<load name="layout_pdf_xml17_loaded_part.xml" query="a" />
			</pd>
			<pd width="2" />
			<pd>
				<load name="layout_pdf_xml17_loaded_part.xml" query="b" />
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_xml9_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="30" cols="6" />
	</Queries>
	<Report fontSize="12" paperType="A4" orientation="landscape" detail_columns="2" column_pad="1">
		<Variables>
			<Variable name="age_avg" value="age" type="average" resetonbreak="male" precalculate="yes" />
			<Variable name="age_avg2" value="age" type="average" precalculate="yes" />
		</Variables>

		<Breaks>
			<Break name="male">
				<BreakHeader>
					<Output>
						<HorizontalLine size="1" color="'Red'" />
						<Line fontSize="13">
							<field width="20" value="(male ? 'Male' : 'Female') + ' break header'" />
							<field width="8" value="v.age_avg" format="'%.2d'" />
							<field width="4" value="r.pageno" />
							<field width="4" value="r.totpages" />
						</Line>
						<HorizontalLine size="1" color="'Red'"/>
					</Output>
				</BreakHeader>

				<BreakFooter>
					<Output>
						<HorizontalLine size="1" color="'Red'" />
						<Line fontSize="13">
							<field width="20" value="(male ? 'Male' : 'Female') + ' break footer'" />
							<field width="8" value="v.age_avg" format="'%.2d'" />
							<field width="4" value="r.pageno" />
							<field width="4" value="r.totpages" />
						</Line>
						<HorizontalLine size="1" bgcolor="'Red'"/>
					</Output>
				</BreakFooter>

				<BreakFields>
					<BreakField value="male" />
				</BreakFields>
			</Break>

			<Break name="adult">
				<BreakHeader>
					<Output>
						<HorizontalLine size="1" color="'Green'" />
						<Line fontSize="13">
							<field width="20" value="((age > 18) ? 'Adult' : 'Kid') + ' break header'" />
							<field width="8" value="v.age_avg" format="'%.2d'" />
							<field width="4" value="r.pageno" />
							<field width="4" value="r.totpages" />
						</Line>
						<HorizontalLine size="1" color="'Green'" />
					</Output>
				</BreakHeader>

				<BreakFooter>
					<Output>
						<HorizontalLine size="1" color="'Green'" />
						<Line fontSize="13">
							<field width="20" value="((age > 18) ? 'Adult' : 'Kid') + ' break footer'" />
							<field width="8" value="v.age_avg" format="'%.2d'" />
							<field width="4" value="r.pageno" />
							<field width="4" value="r.totpages" />
						</Line>
						<HorizontalLine size="1" color="'Green'" />
					</Output>
				</BreakFooter>

				<BreakFields>
					<BreakField value="age > 18" />
				</BreakFields>
			</Break>
		</Breaks>

		<NoData>
			<Output>
				<HorizontalLine size="1" color="'Black'" />
				<Line>
					<field value="'There'" width="6" color="'Red'" bgcolor="'Blue'" bold="yes" />
					<literal width="3" align="'right'" color="'White'" bgcolor="'Black'" >is</literal>
					<field value="'no'" width="3" align="'center'" color="'Lime'" bgcolor="'Teal'" italic="yes" />
					<literal width="5" color="'Aqua'" bgcolor="'Silver'" >data</literal>
					<field value="'here.'" width="5" color="'Fuchsia'" bgcolor="'Green'"  />
				</Line>
				<HorizontalLine size="1" color="'Black'" />
			</Output>
		</NoData>

		<PageHeader>
			<Output>
				<HorizontalLine size="2" color="'Black'"/>
				<Line fontSize="14">
					<field value="printf('Page header: %d / %d', r.pageno, r.totpages)" align="right" />
				</Line>
				<HorizontalLine size="2" color="'Black'"/>
				<HorizontalLine size="4" color="'white'"/>
			</Output>
		</PageHeader>

		<PageFooter>
			<Output>
				<HorizontalLine size="2" color="'Black'"/>
				<Line fontSize="14">
					<field value="printf('Page footer: %d / %d', r.pageno, r.totpages)" align="right" />
				</Line>
				<HorizontalLine size="2" color="'Black'"/>
			</Output>
		</PageFooter>

		<ReportHeader>
			<Output>
				<HorizontalLine size="2" color="'Teal'"/>
				<Line fontSize="14">
					<literal>Yabba dabba doo header </literal>
					<field value="printf('average age: %.2d', v.age_avg2)" />
				</Line>
				<HorizontalLine size="2" color="'Teal'"/>
			</Output>
		</ReportHeader>

		<ReportFooter>
			<Output>
				<HorizontalLine size="2" color="'Teal'"/>
				<Line fontSize="14">
					<literal>Yabba dabba doo footer </literal>
					<field value="printf('average age: %.2d', v.age_avg2)" />
				</Line>
				<HorizontalLine size="2" color="'Teal'"/>
			</Output>
		</ReportFooter>

		<Detail>
			<FieldHeaders>
				<Output>
					<HorizontalLine size="1" bgcolor="'black'"/>
					<Line bgcolor="'0xe5e5e5'">
						<literal width="4" col="1">ID</literal>
						<literal width="1"/>
						<literal width="20" col="2">Name</literal>
						<literal width="1"/>
						<literal width="10" col="3">Property</literal>
						<literal width="1"/>
						<literal width="5" col="4">Age</literal>
						<literal width="1"/>
						<literal width="5" col="5">Adult</literal>
					</Line>
					<HorizontalLine size="1" bgcolor="'black'"/>
					<HorizontalLine size="4" bgcolor="'white'"/>
				</Output>
			</FieldHeaders>

			<FieldDetails>
				<Output>
					<Line>
						<field value="id" width="4" align="right" col="1"/>
						<literal width="1"/>
						<field value="name" width="20" align="left" col="2"/>
						<literal width="1"/>
						<field value="property" width="10" align="'left'" col="3"/>
						<literal width="1"/>
						<field value="age" width="5" format="'%.2d'" align="'right'" col="4"/>
						<literal width="1"/>
						<field value="adult ? 'yes' : 'no'" width="5" align="'center'" col="5"/>
					</Line>
				</Output>
			</FieldDetails>
		</Detail>

	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_xml38_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="0" cols="5" />
	</Queries>
	<Report fontSize="100">
		<NoData>
			<Output>
				<HorizontalLine size="1" color="'Black'" />
				<Line>
					<field fontName="'Arial'" fontSize="20" value="'ABCqwpfgjyb'" color="'Red'" bgcolor="'Blue'" bold="yes" italic="no" />
					<field fontName="'Courier'" fontSize="12" value="'byjgfpwqCBA'" color="'Green'" bgcolor="'BobKratz'" bold="yes" italic="yes" />
					<field fontName="'Pentaluma Script'" fontSize="8" value="'ABCqwpfgjyb'" color="'White'" bgcolor="'Black'" bold="no" italic="yes" />
					<field fontName="'Times New Roman'" fontSize="8" value="'byjgfpwqCBA'" color="'Blue'" bgcolor="'Teal'" bold="no" italic="no" />
				</Line>
				<HorizontalLine size="1" length="1000" color="'Purple'" />
			</Output>
		</NoData>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_xml2_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="5" cols="5" />
	</Queries>
	<Report fontSize="12">
		<NoData>
			<Output>
				<HorizontalLine size="1" color="'Black'" />
				<Line>
					<field value="'There'" width="6" color="'Red'" bgcolor="'Blue'" bold="yes" />
					<literal width="3" align="'right'" color="'White'" bgcolor="'Black'" >is</literal>
					<field value="'no'" width="3" align="'center'" color="'Lime'" bgcolor="'Teal'" italic="yes" />
					<literal width="5" color="'Aqua'" bgcolor="'Silver'" >data</literal>
					<field value="'here.'" width="5" color="'Fuchsia'" bgcolor="'Green'"  />
				</Line>
				<HorizontalLine size="1" color="'Black'" />
			</Output>
		</NoData>

		<ReportHeader>
			<Output>
				<HorizontalLine size="1" color="'Red'" />
				<Line fontSize="14">
					<literal>Flintstones report 1 header</literal>
				</Line>
				<HorizontalLine size="4" bgcolor="'white'"/>
				<HorizontalLine size="2" bgcolor="'black'"/>
				<HorizontalLine size="4" bgcolor="'white'"/>
			</Output>
		</ReportHeader>

		<ReportFooter>
			<Output>
				<HorizontalLine size="1" color="'Red'" />
				<Line fontSize="14">
					<literal>Flintstones report 1 footer</literal>
				</Line>
				<HorizontalLine size="4" bgcolor="'white'"/>
				<HorizontalLine size="2" bgcolor="'black'"/>
				<HorizontalLine size="4" bgcolor="'white'"/>
			</Output>
		</ReportFooter>

		<Detail>
			<FieldHeaders>
				<Output>
					<HorizontalLine size="1" bgcolor="'black'"/>
					<Line bgcolor="'0xe5e5e5'">
						<literal width="4" col="1">ID</literal>
						<literal width="1"/>
						<literal width="20" col="2">Name</literal>
						<literal width="1"/>
						<literal width="10" col="3">Property</literal>
						<literal width="1"/>
						<literal width="5" col="4">Age</literal>
						<literal width="1"/>
						<literal width="5" col="5">Adult</literal>
					</Line>
					<HorizontalLine size="1" bgcolor="'black'"/>
					<HorizontalLine size="4" bgcolor="'white'"/>
				</Output>
			</FieldHeaders>

			<FieldDetails>
				<Output>
					<Line>
						<field value="id" width="4" align="right" col="1"/>
						<literal width="1"/>
						<field value="name" width="20" align="left" col="2"/>
						<literal width="1"/>
						<field value="property" width="10" align="'left'" col="3"/>
						<literal width="1"/>
						<field value="age" width="5" format="'%.2d'" align="'right'" col="4"/>
						<literal width="1"/>
						<field value="adult ? 'yes' : 'no'" width="5" align="'center'" col="5"/>
					</Line>
				</Output>
			</FieldDetails>
		</Detail>

	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/break_suppressblank_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="8" cols="3" />
	</Queries>
	<Report>
		<Breaks>
			<Break name="country">
				<BreakHeader>
					<Output>
						<Line>
							<field value="isnull(city) ? printf('City-state: %s, population %d', country, population) : printf('Country: %s', country)" />
						</Line>
					</Output>
				</BreakHeader>

				<BreakFields>
					<BreakField value="country" />
				</BreakFields>
			</Break>

			<Break name="city" suppressblank="yes">
				<BreakHeader>
					<Output>
						<Line>
							<field value="printf('    City %s, population %d', city, population)" />
						</Line>
					</Output>
				</BreakHeader>

				<BreakFields>
					<BreakField value="city" />
				</BreakFields>
			</Break>
		</Breaks>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_translate_xml1_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport locale="'hu_HU'" translation_domain="translate_test" translation_directory="m.abs_builddir + '/locale'" >
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="9" cols="4" />
	</Queries>
	<Part fontSize="10">
		<pr>
			<pd border_width="2" border_color="'bobkratz'">
				<Report fontSize="12" paperType="A4" orientation="landscape">
					<PageHeader>
						<Output>
							<HorizontalLine size="2" color="'Black'"/>
							<Line fontSize="14">
								<field value="printf(translate('Page header: %d / %d'), r.pageno, r.totpages)" align="right" translate="yes" />
							</Line>
							<HorizontalLine size="2" color="'Black'"/>
						</Output>
					</PageHeader>

					<PageFooter>
						<Output>
							<HorizontalLine size="2" color="'Black'"/>
							<Line fontSize="14">
								<field value="printf(translate('Page footer: %d / %d'), r.pageno, r.totpages)" align="right" translate="yes" />
							</Line>
							<HorizontalLine size="2" color="'Black'"/>
						</Output>
					</PageFooter>

					<Detail>
						<FieldHeaders>
							<Output>
								<HorizontalLine size="1" bgcolor="'black'"/>
								<Line bgcolor="'0xe5e5e5'">
									<literal width="4" col="1">ID</literal>
									<literal width="1"/>
									<literal width="50" translate="yes" col="2">Greetings</literal>
									<literal width="1"/>
									<literal width="7" translate="yes" col="4">Age</literal>
									<literal width="1"/>
									<literal width="7" translate="yes" col="5" align="'center'">Adult</literal>
								</Line>
								<HorizontalLine size="1" bgcolor="'black'"/>
							</Output>
						</FieldHeaders>

						<FieldDetails>
							<Output>
								<Line bgcolor="iif(r.detailcnt%2,'0xe5e5e5','white')">
									<field value="id" width="4" align="right" col="1"/>
									<literal width="1"/>
									<field value="name" format="'Happy birthday, %s!'" width="50" align="justified" col="2" memo="yes" translate="yes" />
									<literal width="1"/>
									<field value="age" width="7" format="'%.2d'" align="'right'" col="4"/>
									<literal width="1"/>
									<field value="adult ? 'yes' : 'no'" width="7" align="'center'" translate="yes" col="5"/>
								</Line>
							</Output>
						</FieldDetails>
					</Detail>
				</Report>
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/custom_variable_xml_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="8" cols="1" />
	</Queries>
	<Report>
		<Variables>
			<Variable name="var1" type="custom" basetype="string" baseexpr="upper(left(a.text, 1))" resultexpr="r.self + r.baseexpr" />
		</Variables>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/variable_resetonbreak_xml_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="5" cols="6" />
	</Queries>
	<Report>
		<Variables>
			<Variable name="var_id_count" value="id" type="count" resetonbreak="adult" />
			<Variable name="var_id_countall" value="id" type="countall" resetonbreak="adult" />
			<Variable name="var_id_sum" value="id" type="sum" resetonbreak="adult" />
			<Variable name="var_id_highest" value="id" type="highest" resetonbreak="adult" />
			<Variable name="var_id_lowest" value="id" type="lowest" resetonbreak="adult" />
			<Variable name="var_id_avg" value="id" type="average" resetonbreak="adult" />
			<Variable name="var_id_avgall" value="id" type="averageall" resetonbreak="adult" />
			<Variable name="var_id2_count" value="id2" type="count" resetonbreak="adult" />
			<Variable name="var_id2_countall" value="id2" type="countall" resetonbreak="adult" />
			<Variable name="var_id2_sum" value="id2" type="sum" resetonbreak="adult" />
			<Variable name="var_id2_highest" value="id2" type="highest" resetonbreak="adult" />
			<Variable name="var_id2_lowest" value="id2" type="lowest" resetonbreak="adult" />
			<Variable name="var_id2_avg" value="id2" type="average" resetonbreak="adult" />
			<Variable name="var_id2_avgall" value="id2" type="averageall" resetonbreak="adult" />
		</Variables>
		<Breaks>
			<Break name="adult">
				<BreakFields>
					<BreakField value="age > 18" />
				</BreakFields>
			</Break>
		</Breaks>
	</Report>
</OpenCReport>
