=== zboszor/OpenCReports/opencreport.dtd
<!ELEMENT OpenCReport (Paths?,Datasources?,Queries?,(Part|Report)*)>
<!ATTLIST OpenCReport
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	precision_bits CDATA #IMPLIED
	rounding_mode (nearest|to_minus_inf|to_inf|to_zero|away_from_zero|faithful) "nearest"
	locale CDATA #IMPLIED
	translation_domain CDATA #IMPLIED
	translation_directory CDATA #IMPLIED >
<!ELEMENT Paths (Path+)>
<!ELEMENT Path EMPTY>
<!ATTLIST Path
    value CDATA #REQUIRED>
<!ELEMENT Datasources (Datasource+)>
<!ELEMENT Datasource EMPTY>
<!ATTLIST Datasource
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	encoding CDATA #IMPLIED
	host CDATA #IMPLIED
	unix_socket CDATA #IMPLIED
	port CDATA #IMPLIED
	dbname CDATA #IMPLIED
	user CDATA #IMPLIED
	password CDATA #IMPLIED
	connstr CDATA #IMPLIED
	optionfile CDATA #IMPLIED
	group CDATA #IMPLIED
	filename CDATA #IMPLIED >
<!ELEMENT Queries (Query)+>
<!ELEMENT Query (#PCDATA)>
<!ATTLIST Query
	name CDATA #REQUIRED
	datasource CDATA #REQUIRED
	value CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	coltypes CDATA #IMPLIED
	follower_for CDATA #IMPLIED
	follower_expr CDATA #IMPLIED >
<!ELEMENT Part (PageHeader|PageFooter|ReportHeader|ReportFooter|pr)*>
<!ATTLIST Part
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	orientation CDATA #IMPLIED
	topMargin CDATA #IMPLIED
	top_margin CDATA #IMPLIED
	bottomMargin CDATA #IMPLIED
	bottom_margin CDATA #IMPLIED
	leftMargin CDATA #IMPLIED
	left_margin CDATA #IMPLIED
	rightMargin CDATA #IMPLIED
	right_margin CDATA #IMPLIED
	paperType CDATA #IMPLIED
	paper_type CDATA #IMPLIED
	iterations CDATA #IMPLIED
	suppressPageHeaderFirstPage CDATA #IMPLIED >
<!ELEMENT pr (pd)+>
<!ATTLIST pr
	layout CDATA #IMPLIED
	newpage CDATA #IMPLIED >
<!ELEMENT pd (Report|load)*>
<!ATTLIST pd
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	border_width CDATA #IMPLIED
	border_color CDATA #IMPLIED
	detail_columns CDATA #IMPLIED
	column_pad CDATA #IMPLIED
	suppress CDATA #IMPLIED >
<!ELEMENT load EMPTY>
<!ATTLIST load
	name CDATA #IMPLIED
	query CDATA #IMPLIED
	iterations CDATA #IMPLIED >
<!ELEMENT Report ((Alternate|NoData)|(Breaks?,Variables?)|PageHeader|PageFooter|ReportHeader|ReportFooter|(Detail|Graph|Chart)*|xi:include)* >
<!ATTLIST Report
	pagesAcross CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	orientation CDATA #IMPLIED
	topMargin CDATA #IMPLIED
	top_margin CDATA #IMPLIED
	bottomMargin CDATA #IMPLIED
	bottom_margin CDATA #IMPLIED
	leftMargin CDATA #IMPLIED
	left_margin CDATA #IMPLIED
	rightMargin CDATA #IMPLIED
	right_margin CDATA #IMPLIED
	paperType CDATA #IMPLIED
	paper_type CDATA #IMPLIED
	iterations CDATA #IMPLIED
	suppress CDATA #IMPLIED
	suppressPageHeaderFirstPage CDATA #IMPLIED
	query CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	field_header_priority CDATA #IMPLIED
	detail_columns CDATA #IMPLIED
	column_pad CDATA #IMPLIED >
<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
	href CDATA #REQUIRED >
<!ELEMENT Alternate (NoData) >
<!ELEMENT NoData (Output) >
<!ELEMENT ReportHeader (Output)* >
<!ELEMENT PageHeader (Output)* >
<!ELEMENT ReportFooter (Output)* >
<!ELEMENT PageFooter (Output)* >
<!ELEMENT Output (Line | GeneratedLine | HorizontalLine | Image | Barcode | ImageEnd)* >
<!ATTLIST Output
    suppress CDATA #IMPLIED >
<!ELEMENT Line (field | literal | Image | Barcode)* >
<!ATTLIST Line
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	suppress CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT field (#PCDATA) >
<!ATTLIST field
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	format CDATA #IMPLIED
	width CDATA #IMPLIED
	align CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	link CDATA #IMPLIED
	memo CDATA #IMPLIED
	memo_hyphenate CDATA #IMPLIED
	memo_wrap_chars CDATA #IMPLIED
	memo_max_lines CDATA #IMPLIED
	translate CDATA #IMPLIED
	col CDATA #IMPLIED >
<!ELEMENT literal (#PCDATA) >
<!ATTLIST literal
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	format CDATA #IMPLIED
	width CDATA #IMPLIED
	align CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	link CDATA #IMPLIED
	memo CDATA #IMPLIED
	memo_hyphenate CDATA #IMPLIED
	memo_wrap_chars CDATA #IMPLIED
	memo_max_lines CDATA #IMPLIED
	translate CDATA #IMPLIED
	col CDATA #IMPLIED >
<!ELEMENT HorizontalLine EMPTY>
<!ATTLIST HorizontalLine
	size CDATA #IMPLIED
	align CDATA #IMPLIED
	indent CDATA #IMPLIED
	length CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	suppress CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT Image EMPTY >
<!ATTLIST Image
	value CDATA #REQUIRED
	suppress CDATA #IMPLIED
	type CDATA #REQUIRED
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	align CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	text_width CDATA #REQUIRED
	textWidth CDATA #REQUIRED >
<!ATTLIST Barcode
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	suppress CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	type CDATA #IMPLIED
	width CDATA #REQUIRED
	height CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT GeneratedLine EMPTY>
<!ATTLIST GeneratedLine
	element_type CDATA #REQUIRED
	line_font_name CDATA #IMPLIED
	line_font_size CDATA #IMPLIED
	line_bold CDATA #IMPLIED
	line_italic CDATA #IMPLIED
	line_italics CDATA #IMPLIED
	line_suppress CDATA #IMPLIED
	line_color CDATA #IMPLIED
	line_colour CDATA #IMPLIED
	line_bgcolor CDATA #IMPLIED
	line_bgcolour CDATA #IMPLIED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	align CDATA #IMPLIED
	alignment CDATA #IMPLIED
	color CDATA #IMPLIED
	colour CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	bgcolour CDATA #IMPLIED
	font_name CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	format CDATA #IMPLIED
	link CDATA #IMPLIED
	translate CDATA #IMPLIED
	memo CDATA #IMPLIED
	hyphenate CDATA #IMPLIED
	wrap_chars CDATA #IMPLIED
	max_lines CDATA #IMPLIED
	imgtype CDATA #IMPLIED
	text_width CDATA #IMPLIED
	bctype CDATA #IMPLIED >
<!ELEMENT Detail ((FieldHeader|FieldHeaders)?, (FieldDetail|FieldDetails)?, (FieldFooter|FieldFooters)?) >
<!ELEMENT FieldHeader (Output)* >
<!ELEMENT FieldHeaders (Output)* >
<!ELEMENT FieldDetail (Output)* >
<!ATTLIST FieldDetail
	matched CDATA #IMPLIED
	overlay CDATA #IMPLIED >
<!ELEMENT FieldDetails (Output)* >
<!ATTLIST FieldDetails
	matched CDATA #IMPLIED
	overlay CDATA #IMPLIED >
<!ELEMENT FieldFooter (Output)* >
<!ELEMENT FieldFooters (Output)* >
<!ELEMENT Graph (Plot+) >
<!ATTLIST Graph
	name CDATA #IMPLIED
	type CDATA #REQUIRED
	subtype CDATA #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	bold_titles CDATA #IMPLIED
	title CDATA #IMPLIED
	legend_bg_color CDATA #IMPLIED
	legend_orientation CDATA #IMPLIED
	draw_x_line CDATA #IMPLIED
	draw_y_line CDATA #IMPLIED
	grid_color CDATA #IMPLIED
	x_axis_title CDATA #IMPLIED
	y_axis_title CDATA #IMPLIED
	y_axis_mod CDATA #IMPLIED
	y_axis_title_right CDATA #IMPLIED
	y_axis_decimals CDATA #IMPLIED
	y_axis_decimals_right CDATA #IMPLIED >
<!ELEMENT Plot EMPTY>
<!ATTLIST Plot
	axis CDATA #IMPLIED
	field CDATA #IMPLIED
	label CDATA #IMPLIED
	side CDATA #IMPLIED
	disabled CDATA #IMPLIED
	color CDATA #IMPLIED >
<!ELEMENT Chart (HeaderRow?,Row?)>
<!ATTLIST Chart
	name CDATA #IMPLIED
	title CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	cell_width CDATA #IMPLIED
	cell_height CDATA #IMPLIED
	cell_width_padding CDATA #IMPLIED
	cell_height_padding CDATA #IMPLIED
	label_width CDATA #IMPLIED
	header_row CDATA #IMPLIED >
<!ELEMENT HeaderRow EMPTY>
<!ATTLIST HeaderRow
	query CDATA #IMPLIED
	field CDATA #IMPLIED
	colspan CDATA #IMPLIED >
<!ELEMENT Row EMPTY>
<!ATTLIST Row
	row CDATA #IMPLIED
	bar_start CDATA #IMPLIED
	bar_end CDATA #IMPLIED
	label CDATA #IMPLIED
	bar_label CDATA #IMPLIED
	bar_color CDATA #IMPLIED
	bar_label_color CDATA #IMPLIED >
<!ELEMENT Breaks (Break)* >
<!ELEMENT Break (BreakHeader | BreakFooter | BreakFields)* >
<!ATTLIST Break
	name CDATA #REQUIRED
	headernewpage CDATA #IMPLIED
	suppressblank CDATA #IMPLIED
	newpage CDATA #IMPLIED >
<!ELEMENT BreakHeader (Output)* >
<!ELEMENT BreakFooter (Output)* >
<!ELEMENT BreakFields (BreakField)* >
<!ELEMENT BreakField EMPTY>
<!ATTLIST BreakField
	value CDATA #REQUIRED >
<!ELEMENT Variables (Variable)* >
<!ELEMENT Variable EMPTY >
<!ATTLIST Variable
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	baseexpr CDATA #IMPLIED
	intermedexpr CDATA #IMPLIED
	intermed2expr CDATA #IMPLIED
	resultexpr CDATA #IMPLIED
	type (expression|count|sum|average|lowest|highest|custom) "sum"
	basetype (number|string|datetime) "number"
	resetonbreak CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	delayed CDATA #IMPLIED >

=== zboszor/OpenCReports/tests/layout_xml39_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport size_unit="rlib">
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="0" cols="5" />
	</Queries>
	<Report fontSize="100">
		<NoData>
			<Output>
				<HorizontalLine size="1" color="'Black'" />
				<Line fontSize="10">
					<field width="4" fontName="'Arial'" fontSize="20" value="'ABCqwpfgjyb'" color="'Red'" bgcolor="'Blue'" bold="yes" italic="no" />
					<field width="4" fontName="'Courier'" fontSize="12" value="'byjgfpwqCBA'" color="'Green'" bgcolor="'BobKratz'" bold="yes" italic="yes" />
					<field width="4" fontName="'Petaluma Script'" fontSize="8" value="'ABCqwpfgjyb'" color="'White'" bgcolor="'Black'" bold="no" italic="yes" />
					<field width="4" fontName="'Times New Roman'" fontSize="8" value="'byjgfpwqCBA'" color="'Blue'" bgcolor="'Teal'" bold="no" italic="no" />
				</Line>
				<HorizontalLine size="1" length="1000" color="'Purple'" />
			</Output>
		</NoData>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_xml13_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="5" cols="5" />
	</Queries>
	<Part>
		<pr>
			<pd>
				<load name="layout_pdf_xml13_loaded_part.xml" />
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_xml33_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="120" cols="6" />
	</Queries>
	<Part fontSize="10" suppressPageHeaderFirstPage="yes">
		<pr>
			<pd>
				<Report query="nonexisting">
					<NoData>
						<Output>
							<HorizontalLine size="400" color="'yellow'" />
						</Output>
					</NoData>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd>
				<Report query="nonexisting">
					<NoData>
						<Output>
							<HorizontalLine size="1" color="'red'" />
						</Output>
					</NoData>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd detail_columns="2" column_pad="0.2" height="25" border_width="2" border_color="'bobkratz'">
				<Report fontSize="12" paperType="A4" orientation="landscape">
					<NoData>
						<Output>
							<HorizontalLine size="1" color="'Black'" />
							<Line>
								<field value="'There'" width="6" color="'Red'" bgcolor="'Blue'" bold="yes" />
								<literal width="3" align="'right'" color="'White'" bgcolor="'Black'" >is</literal>
								<field value="'no'" width="3" align="'center'" color="'Lime'" bgcolor="'Teal'" italic="yes" />
								<literal width="5" color="'Aqua'" bgcolor="'Silver'" >data</literal>
								<field value="'here.'" width="5" color="'Fuchsia'" bgcolor="'Green'"  />
							</Line>
							<HorizontalLine size="1" color="'Black'" />
						</Output>
					</NoData>

					<PageHeader>
						<Output>
							<HorizontalLine size="2" color="'Black'"/>
							<Line fontSize="14">
								<field value="printf('Page header: %d / %d', r.pageno, r.totpages)" align="right" />
							</Line>
							<HorizontalLine size="2" color="'Black'"/>
							<HorizontalLine size="4" color="'white'"/>
						</Output>
					</PageHeader>

					<PageFooter>
						<Output>
							<HorizontalLine size="2" color="'Black'"/>
							<Line fontSize="14">
								<field value="printf('Page footer: %d / %d', r.pageno, r.totpages)" align="right" />
							</Line>
							<HorizontalLine size="2" color="'Black'"/>
						</Output>
					</PageFooter>

					<Detail>
						<FieldHeaders>
							<Output>
								<HorizontalLine size="1" bgcolor="'black'"/>
								<Line bgcolor="'0xe5e5e5'">
									<literal width="3" col="1">ID</literal>
									<literal width="1"/>
									<literal width="20" col="2">Name</literal>
									<literal width="1"/>
									<literal width="6" col="3">lineno</literal>
									<literal width="1"/>
									<literal width="6" col="4">rownum</literal>
									<literal width="1"/>
									<literal width="9" col="5">detailcnt</literal>
								</Line>
								<HorizontalLine size="1" bgcolor="'black'"/>
								<HorizontalLine size="4" bgcolor="'white'"/>
							</Output>
						</FieldHeaders>

						<FieldDetails>
							<Output>
								<Line bgcolor="iif(r.detailcnt%2,'0xe5e5e5','white')">
									<field value="id" width="3" align="right" col="1"/>
									<literal width="1"/>
									<field value="name" width="20" align="left" col="2"/>
									<literal width="1"/>
									<field value="r.lineno" width="6" align="'right'" col="3"/>
									<literal width="1"/>
									<field value="rownum()" width="6" align="'right'" col="4"/>
									<literal width="1"/>
									<field value="r.detailcnt" width="9" align="'right'" col="5"/>
								</Line>
							</Output>
						</FieldDetails>
					</Detail>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd>
				<Report query="nonexisting">
					<NoData>
						<Output>
							<HorizontalLine size="1" color="'red'" />
						</Output>
					</NoData>
				</Report>
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/csvquery2.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="csv" type="csv" />
		<Datasource name="array" type="array" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="csv" value="csvquery.csv" coltypes="coltypes" />
	</Queries>
	<Queries>
		<Query name="b" datasource="array" value="array2" coltypes="coltypes" rows="2" cols="5" follower_for="a" />
	</Queries>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_pdf_xml36_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport size_unit="points">
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="9" cols="5" />
	</Queries>
	<Part fontName="Petaluma Script">
		<pr>
			<pd detail_columns="2" column_pad="2" border_width="2" border_color="'bobkratz'">
				<Report fontSize="12" paperType="A4" orientation="landscape">
					<PageHeader>
						<Output>
							<HorizontalLine size="2" color="'Black'"/>
							<Line fontSize="14">
								<field value="printf('Page header: %d / %d', r.pageno, r.totpages)" align="right" />
							</Line>
							<HorizontalLine size="2" color="'Black'"/>
						</Output>
					</PageHeader>

					<PageFooter>
						<Output>
							<HorizontalLine size="2" color="'Black'"/>
							<Line fontSize="14">
								<field value="printf('Page footer: %d / %d', r.pageno, r.totpages)" align="right" />
							</Line>
							<HorizontalLine size="2" color="'Black'"/>
						</Output>
					</PageFooter>

					<Detail>
						<FieldHeaders>
							<Output>
								<HorizontalLine size="1" bgcolor="'black'"/>
								<Line bgcolor="'0xe5e5e5'">
									<literal width="30" col="1">ID</literal>
									<literal width="5"/>
									<literal width="160" col="2">Name</literal>
									<literal width="5"/>
									<literal width="75" col="3" align="'center'">Property</literal>
									<literal width="5"/>
									<literal width="60" col="4">Age</literal>
									<literal width="5"/>
									<literal width="60" col="5" align="'center'">Adult</literal>
								</Line>
								<HorizontalLine size="1" bgcolor="'black'"/>
							</Output>
						</FieldHeaders>

						<FieldDetails>
							<Output>
								<Line bgcolor="iif(r.detailcnt%2,'0xe5e5e5','white')">
									<field value="id" width="30" align="right" col="1"/>
									<literal width="5"/>
									<field value="name" width="160" align="left" col="2" memo="yes" memo_wrap_chars="yes" />
									<literal width="5"/>
									<field value="property" width="75" align="'center'" col="3" memo="yes"/>
									<literal width="5"/>
									<field value="age" width="60" format="'%.2d'" align="'right'" col="4"/>
									<literal width="5"/>
									<field value="adult ? 'yes' : 'no'" width="60" align="'center'" col="5"/>
								</Line>
							</Output>
						</FieldDetails>
					</Detail>
				</Report>
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_matched_overlay_text_indent_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="7" cols="6" />
	</Queries>
	<Report>
		<Detail>
			<FieldHeaders>
				<Output>
					<Line>
						<field value="'Family name'" width="15" />
						<literal width="1"/>
						<field value="'Husband'" width="10" />
						<literal width="1"/>
						<field value="'Wife'" width="10" />
						<literal width="1"/>
						<field value="'Child'" width="10" />
					</Line>
				</Output>
			</FieldHeaders>
			<FieldDetails matched="surname" overlay="yes">
				<Output>
					<Line>
						<field value="surname" width="15" color="r.matched ? 'transparent' : 'blue'" bgcolor="r.matched ? 'transparent' : 'yellow'" />
						<literal width="1"/>
						<field value="firstname" width="10" align="'center'" indent="indent" bgcolor="male ? '#8080ff' : '#ff8080'" />
					</Line>
				</Output>
			</FieldDetails>
		</Detail>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_xml50_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="120" cols="6" />
		<Query name="h" datasource="myarray" value="'header_array'" coltypes="'header_coltypes'" rows="5" cols="3" />
	</Queries>
	<Part fontSize="10">
		<pr>
			<pd>
				<Report fontSize="12">
					<PageHeader>
						<Output>
							<HorizontalLine size="1" color="'red'"/>
							<Line>
								<literal>Page header</literal>
							</Line>
							<HorizontalLine size="1" color="'red'"/>
						</Output>
					</PageHeader>

					<PageFooter>
						<Output>
							<HorizontalLine size="1" color="'green'"/>
							<Line>
								<literal>Page footer</literal>
							</Line>
							<HorizontalLine size="1" color="'green'"/>
						</Output>
					</PageFooter>

					<Detail>
						<FieldHeaders>
							<Output>
								<HorizontalLine size="1" color="'black'"/>
								<GeneratedLine query="'h'" element_type="h.element_type"
								               bgcolor="'0xe5e5e5'"
								               value="h.label" width="h.col_width"/>
								<HorizontalLine size="1" color="'black'"/>
							</Output>
						</FieldHeaders>

						<FieldDetails>
							<Output>
								<Line bgcolor="iif(r.detailcnt%2,'0xe5e5e5','white')">
									<field value="id" width="4" align="'right'"/>
									<literal width="1"/>
									<field value="name" width="20"/>
									<literal width="1"/>
									<field value="property" width="10"/>
									<literal width="1"/>
									<field value="age" width="6" align="'right'"/>
									<literal width="1"/>
									<field value="adult ? 'yes' : 'no'" width="5" align="'center'"/>
								</Line>
							</Output>
						</FieldDetails>
					</Detail>
				</Report>
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/page_header_footer_vars_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="82" cols="2" />
	</Queries>
	<Report>
		<Variables>
			<Variable name="mysum" value="num" type="sum" />
		</Variables>
		<PageHeader>
			<Output>
				<HorizontalLine size="1" bgcolor="'black'"/>
				<Line>
					<literal>Fruit count </literal>
					<field value="r.pageno = 1 ? 0 : prevval(v.mysum)"/>
					<literal> (carry over from previous page)</literal>
				</Line>
				<HorizontalLine size="1" bgcolor="'black'"/>
			</Output>
		</PageHeader>
		<PageFooter>
			<Output>
				<HorizontalLine size="1" bgcolor="'black'"/>
				<Line>
					<literal>Fruit count </literal>
					<field value="v.mysum"/>
					<field value="r.pageno = r.totpages ? ' (total count)' : ' (carry over to next page)'" />
				</Line>
				<HorizontalLine size="1" bgcolor="'black'"/>
			</Output>
		</PageFooter>
		<Detail>
			<FieldHeaders>
				<Output>
					<Line>
						<literal width="30">Type</literal>
						<literal width="1"/>
						<literal width="6">Number</literal>
						<literal width="1"/>
						<literal width="11">Running sum</literal>
					</Line>
				</Output>
			</FieldHeaders>
			<FieldDetails>
				<Output>
					<Line>
						<field value="type" width="30" align="left"/>
						<literal width="1"/>
						<field value="num" width="6" align="right"/>
						<literal width="1"/>
						<field value="v.mysum" width="11" align="right"/>
					</Line>
				</Output>
			</FieldDetails>
		</Detail>
	</Report>
</OpenCReport>
