=== zboszor/OpenCReports/opencreport.dtd
<!ELEMENT OpenCReport (Paths?,Datasources?,Queries?,(Part|Report)*)>
<!ATTLIST OpenCReport
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	precision_bits CDATA #IMPLIED
	rounding_mode (nearest|to_minus_inf|to_inf|to_zero|away_from_zero|faithful) "nearest"
	locale CDATA #IMPLIED
	translation_domain CDATA #IMPLIED
	translation_directory CDATA #IMPLIED >
<!ELEMENT Paths (Path+)>
<!ELEMENT Path EMPTY>
<!ATTLIST Path
    value CDATA #REQUIRED>
<!ELEMENT Datasources (Datasource+)>
<!ELEMENT Datasource EMPTY>
<!ATTLIST Datasource
	name CDATA #REQUIRED
	type CDATA #REQUIRED
	encoding CDATA #IMPLIED
	host CDATA #IMPLIED
	unix_socket CDATA #IMPLIED
	port CDATA #IMPLIED
	dbname CDATA #IMPLIED
	user CDATA #IMPLIED
	password CDATA #IMPLIED
	connstr CDATA #IMPLIED
	optionfile CDATA #IMPLIED
	group CDATA #IMPLIED
	filename CDATA #IMPLIED >
<!ELEMENT Queries (Query)+>
<!ELEMENT Query (#PCDATA)>
<!ATTLIST Query
	name CDATA #REQUIRED
	datasource CDATA #REQUIRED
	value CDATA #IMPLIED
	rows CDATA #IMPLIED
	cols CDATA #IMPLIED
	coltypes CDATA #IMPLIED
	follower_for CDATA #IMPLIED
	follower_expr CDATA #IMPLIED >
<!ELEMENT Part (PageHeader|PageFooter|ReportHeader|ReportFooter|pr)*>
<!ATTLIST Part
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	orientation CDATA #IMPLIED
	topMargin CDATA #IMPLIED
	top_margin CDATA #IMPLIED
	bottomMargin CDATA #IMPLIED
	bottom_margin CDATA #IMPLIED
	leftMargin CDATA #IMPLIED
	left_margin CDATA #IMPLIED
	rightMargin CDATA #IMPLIED
	right_margin CDATA #IMPLIED
	paperType CDATA #IMPLIED
	paper_type CDATA #IMPLIED
	iterations CDATA #IMPLIED
	suppressPageHeaderFirstPage CDATA #IMPLIED >
<!ELEMENT pr (pd)+>
<!ATTLIST pr
	layout CDATA #IMPLIED
	newpage CDATA #IMPLIED >
<!ELEMENT pd (Report|load)*>
<!ATTLIST pd
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	border_width CDATA #IMPLIED
	border_color CDATA #IMPLIED
	detail_columns CDATA #IMPLIED
	column_pad CDATA #IMPLIED
	suppress CDATA #IMPLIED >
<!ELEMENT load EMPTY>
<!ATTLIST load
	name CDATA #IMPLIED
	query CDATA #IMPLIED
	iterations CDATA #IMPLIED >
<!ELEMENT Report ((Alternate|NoData)|(Breaks?,Variables?)|PageHeader|PageFooter|ReportHeader|ReportFooter|(Detail|Graph|Chart)*|xi:include)* >
<!ATTLIST Report
	pagesAcross CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	size_unit CDATA #IMPLIED
	noquery_show_nodata CDATA #IMPLIED
	report_height_after_last CDATA #IMPLIED
	follower_match_single CDATA #IMPLIED
	orientation CDATA #IMPLIED
	topMargin CDATA #IMPLIED
	top_margin CDATA #IMPLIED
	bottomMargin CDATA #IMPLIED
	bottom_margin CDATA #IMPLIED
	leftMargin CDATA #IMPLIED
	left_margin CDATA #IMPLIED
	rightMargin CDATA #IMPLIED
	right_margin CDATA #IMPLIED
	paperType CDATA #IMPLIED
	paper_type CDATA #IMPLIED
	iterations CDATA #IMPLIED
	suppress CDATA #IMPLIED
	suppressPageHeaderFirstPage CDATA #IMPLIED
	query CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	field_header_priority CDATA #IMPLIED
	detail_columns CDATA #IMPLIED
	column_pad CDATA #IMPLIED >
<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
	href CDATA #REQUIRED >
<!ELEMENT Alternate (NoData) >
<!ELEMENT NoData (Output) >
<!ELEMENT ReportHeader (Output)* >
<!ELEMENT PageHeader (Output)* >
<!ELEMENT ReportFooter (Output)* >
<!ELEMENT PageFooter (Output)* >
<!ELEMENT Output (Line | GeneratedLine | HorizontalLine | Image | Barcode | ImageEnd)* >
<!ATTLIST Output
    suppress CDATA #IMPLIED >
<!ELEMENT Line (field | literal | Image | Barcode)* >
<!ATTLIST Line
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	suppress CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT field (#PCDATA) >
<!ATTLIST field
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	format CDATA #IMPLIED
	width CDATA #IMPLIED
	align CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	link CDATA #IMPLIED
	memo CDATA #IMPLIED
	memo_hyphenate CDATA #IMPLIED
	memo_wrap_chars CDATA #IMPLIED
	memo_max_lines CDATA #IMPLIED
	translate CDATA #IMPLIED
	col CDATA #IMPLIED >
<!ELEMENT literal (#PCDATA) >
<!ATTLIST literal
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	format CDATA #IMPLIED
	width CDATA #IMPLIED
	align CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	fontName CDATA #IMPLIED
	font_name CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	link CDATA #IMPLIED
	memo CDATA #IMPLIED
	memo_hyphenate CDATA #IMPLIED
	memo_wrap_chars CDATA #IMPLIED
	memo_max_lines CDATA #IMPLIED
	translate CDATA #IMPLIED
	col CDATA #IMPLIED >
<!ELEMENT HorizontalLine EMPTY>
<!ATTLIST HorizontalLine
	size CDATA #IMPLIED
	align CDATA #IMPLIED
	indent CDATA #IMPLIED
	length CDATA #IMPLIED
	fontSize CDATA #IMPLIED
	font_size CDATA #IMPLIED
	suppress CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT Image EMPTY >
<!ATTLIST Image
	value CDATA #REQUIRED
	suppress CDATA #IMPLIED
	type CDATA #REQUIRED
	width CDATA #REQUIRED
	height CDATA #REQUIRED
	align CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	text_width CDATA #REQUIRED
	textWidth CDATA #REQUIRED >
<!ATTLIST Barcode
	value CDATA #REQUIRED
	delayed CDATA #IMPLIED
	suppress CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	type CDATA #IMPLIED
	width CDATA #REQUIRED
	height CDATA #IMPLIED
	color CDATA #IMPLIED
	bgcolor CDATA #IMPLIED >
<!ELEMENT GeneratedLine EMPTY>
<!ATTLIST GeneratedLine
	element_type CDATA #REQUIRED
	line_font_name CDATA #IMPLIED
	line_font_size CDATA #IMPLIED
	line_bold CDATA #IMPLIED
	line_italic CDATA #IMPLIED
	line_italics CDATA #IMPLIED
	line_suppress CDATA #IMPLIED
	line_color CDATA #IMPLIED
	line_colour CDATA #IMPLIED
	line_bgcolor CDATA #IMPLIED
	line_bgcolour CDATA #IMPLIED
	delayed CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	suppress CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	align CDATA #IMPLIED
	alignment CDATA #IMPLIED
	color CDATA #IMPLIED
	colour CDATA #IMPLIED
	bgcolor CDATA #IMPLIED
	bgcolour CDATA #IMPLIED
	font_name CDATA #IMPLIED
	font_size CDATA #IMPLIED
	bold CDATA #IMPLIED
	italic CDATA #IMPLIED
	italics CDATA #IMPLIED
	format CDATA #IMPLIED
	link CDATA #IMPLIED
	translate CDATA #IMPLIED
	memo CDATA #IMPLIED
	hyphenate CDATA #IMPLIED
	wrap_chars CDATA #IMPLIED
	max_lines CDATA #IMPLIED
	imgtype CDATA #IMPLIED
	text_width CDATA #IMPLIED
	bctype CDATA #IMPLIED >
<!ELEMENT Detail ((FieldHeader|FieldHeaders)?, (FieldDetail|FieldDetails)?, (FieldFooter|FieldFooters)?) >
<!ELEMENT FieldHeader (Output)* >
<!ELEMENT FieldHeaders (Output)* >
<!ELEMENT FieldDetail (Output)* >
<!ATTLIST FieldDetail
	matched CDATA #IMPLIED
	overlay CDATA #IMPLIED >
<!ELEMENT FieldDetails (Output)* >
<!ATTLIST FieldDetails
	matched CDATA #IMPLIED
	overlay CDATA #IMPLIED >
<!ELEMENT FieldFooter (Output)* >
<!ELEMENT FieldFooters (Output)* >
<!ELEMENT Graph (Plot+) >
<!ATTLIST Graph
	name CDATA #IMPLIED
	type CDATA #REQUIRED
	subtype CDATA #REQUIRED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
	bold_titles CDATA #IMPLIED
	title CDATA #IMPLIED
	legend_bg_color CDATA #IMPLIED
	legend_orientation CDATA #IMPLIED
	draw_x_line CDATA #IMPLIED
	draw_y_line CDATA #IMPLIED
	grid_color CDATA #IMPLIED
	x_axis_title CDATA #IMPLIED
	y_axis_title CDATA #IMPLIED
	y_axis_mod CDATA #IMPLIED
	y_axis_title_right CDATA #IMPLIED
	y_axis_decimals CDATA #IMPLIED
	y_axis_decimals_right CDATA #IMPLIED >
<!ELEMENT Plot EMPTY>
<!ATTLIST Plot
	axis CDATA #IMPLIED
	field CDATA #IMPLIED
	label CDATA #IMPLIED
	side CDATA #IMPLIED
	disabled CDATA #IMPLIED
	color CDATA #IMPLIED >
<!ELEMENT Chart (HeaderRow?,Row?)>
<!ATTLIST Chart
	name CDATA #IMPLIED
	title CDATA #IMPLIED
	cols CDATA #IMPLIED
	rows CDATA #IMPLIED
	cell_width CDATA #IMPLIED
	cell_height CDATA #IMPLIED
	cell_width_padding CDATA #IMPLIED
	cell_height_padding CDATA #IMPLIED
	label_width CDATA #IMPLIED
	header_row CDATA #IMPLIED >
<!ELEMENT HeaderRow EMPTY>
<!ATTLIST HeaderRow
	query CDATA #IMPLIED
	field CDATA #IMPLIED
	colspan CDATA #IMPLIED >
<!ELEMENT Row EMPTY>
<!ATTLIST Row
	row CDATA #IMPLIED
	bar_start CDATA #IMPLIED
	bar_end CDATA #IMPLIED
	label CDATA #IMPLIED
	bar_label CDATA #IMPLIED
	bar_color CDATA #IMPLIED
	bar_label_color CDATA #IMPLIED >
<!ELEMENT Breaks (Break)* >
<!ELEMENT Break (BreakHeader | BreakFooter | BreakFields)* >
<!ATTLIST Break
	name CDATA #REQUIRED
	headernewpage CDATA #IMPLIED
	suppressblank CDATA #IMPLIED
	newpage CDATA #IMPLIED >
<!ELEMENT BreakHeader (Output)* >
<!ELEMENT BreakFooter (Output)* >
<!ELEMENT BreakFields (BreakField)* >
<!ELEMENT BreakField EMPTY>
<!ATTLIST BreakField
	value CDATA #REQUIRED >
<!ELEMENT Variables (Variable)* >
<!ELEMENT Variable EMPTY >
<!ATTLIST Variable
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	baseexpr CDATA #IMPLIED
	intermedexpr CDATA #IMPLIED
	intermed2expr CDATA #IMPLIED
	resultexpr CDATA #IMPLIED
	type (expression|count|sum|average|lowest|highest|custom) "sum"
	basetype (number|string|datetime) "number"
	resetonbreak CDATA #IMPLIED
	precalculate CDATA #IMPLIED
	delayed CDATA #IMPLIED >

=== zboszor/OpenCReports/tests/layout_xml52_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="120" cols="6" />
		<Query name="h" datasource="myarray" value="'header_array'" coltypes="'header_coltypes'" rows="9" cols="5" />
	</Queries>
	<Part fontSize="10">
		<pr>
			<pd detail_columns="2" column_pad="0.2">
				<Report fontSize="12">
					<PageHeader>
						<Output>
							<HorizontalLine size="1" color="'red'"/>
							<Line>
								<literal>Page header</literal>
							</Line>
							<HorizontalLine size="1" color="'red'"/>
						</Output>
					</PageHeader>

					<PageFooter>
						<Output>
							<HorizontalLine size="1" color="'green'"/>
							<Line>
								<literal>Page footer</literal>
							</Line>
							<HorizontalLine size="1" color="'green'"/>
						</Output>
					</PageFooter>

					<Detail>
						<FieldHeaders>
							<Output>
								<HorizontalLine size="1" color="'black'"/>
								<GeneratedLine query="'h'" element_type="h.element_type"
								               bgcolor="'0xe5e5e5'"
								               value="h.label" width="h.col_width"
								               align="h.col_align"/>
								<HorizontalLine size="1" color="'black'"/>
							</Output>
						</FieldHeaders>

						<FieldDetails>
							<Output>
								<!--
								  GeneratedLine in FieldDetails: column layout and value
								  expression come from the 'h' side query.  The value
								  expression h.value is an expression string that references
								  a main-query column by name; eval() parses and evaluates
								  it so the actual field data is displayed.  The per-element
								  bgcolor uses a.age from the main query — demonstrating
								  that both queries can be used for control elements.
								-->
								<GeneratedLine query="'h'" element_type="h.element_type"
								               value="eval(h.value)" width="h.col_width"
								               align="h.col_align"
								               bgcolor="iif(a.age > 20,'0xffe0e0','white')"/>
							</Output>
						</FieldDetails>
					</Detail>
				</Report>
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/tests/ocrpt_part_xml_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Part>
		<pr>
			<pd>
				<Report>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd>
				<Report>
				</Report>
				<Report>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd>
				<Report>
				</Report>
			</pd>
			<pd>
				<Report>
				</Report>
			</pd>
		</pr>
	</Part>
	<Part>
		<pr>
			<pd>
				<Report>
				</Report>
			</pd>
			<pd>
				<Report>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd>
				<Report>
				</Report>
			</pd>
		</pr>
		<pr>
			<pd>
				<Report>
				</Report>
				<Report>
				</Report>
			</pd>
		</pr>
	</Part>
	<Report>
	</Report>
	<Report>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_matched_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="7" cols="5" />
	</Queries>
	<Report>
		<Detail>
			<FieldHeaders>
				<Output>
					<Line>
						<field value="'Name'" width="30" />
						<literal width="1"/>
						<field value="'Has match'" width="9" />
					</Line>
				</Output>
			</FieldHeaders>
			<FieldDetails matched="surname">
				<Output>
					<Line>
						<field value="firstname + ' ' + surname" width="30" />
						<literal width="1"/>
						<field value="r.matched ? 'yes' : 'no'" width="9" align="r.matched ? 'left' : 'right'" />
					</Line>
				</Output>
			</FieldDetails>
		</Detail>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/ocrpt_break_multi2_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="6" cols="4" />
	</Queries>
	<Report>
		<Breaks>
			<Break name="male">
				<BreakFields>
					<BreakField value="male" />
				</BreakFields>
			</Break>
			<Break name="adult">
				<BreakFields>
					<BreakField value="age > 18" />
				</BreakFields>
			</Break>
		</Breaks>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/ocrpt_variable_expression_xml_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="3" cols="5" />
	</Queries>
	<Report>
		<Variables>
			<Variable name="var2" value="id + 2" type="expression" />
			<Variable name="var1" value="id + 1" type="expression" />
		</Variables>
	</Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_xml49_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="120" cols="6" />
	</Queries>
	<Part fontSize="10">
		<pr>
			<pd detail_columns="2" column_pad="0.2">
				<Report fontSize="12">
					<PageHeader>
						<Output>
							<HorizontalLine size="1" color="'red'"/>
							<Line>
								<literal>Page header</literal>
							</Line>
							<HorizontalLine size="1" color="'red'"/>
						</Output>
					</PageHeader>

					<PageFooter>
						<Output>
							<HorizontalLine size="1" color="'green'"/>
							<Line>
								<literal>Page footer</literal>
							</Line>
							<HorizontalLine size="1" color="'green'"/>
						</Output>
					</PageFooter>

					<Detail>
						<FieldHeaders>
							<Output>
								<HorizontalLine size="1" color="'black'"/>
								<Line bgcolor="'0xe5e5e5'">
									<literal width="4">ID</literal>
									<literal width="1"/>
									<literal width="20">Name</literal>
									<literal width="1"/>
									<literal width="10">Property</literal>
									<literal width="1"/>
									<literal width="6">Age</literal>
									<literal width="1"/>
									<literal width="5">Adult</literal>
								</Line>
								<HorizontalLine size="1" color="'black'"/>
							</Output>
						</FieldHeaders>

						<FieldDetails>
							<Output>
								<Line bgcolor="iif(r.detailcnt%2,'0xe5e5e5','white')">
									<field value="id" width="4" align="'right'"/>
									<literal width="1"/>
									<field value="name" width="20"/>
									<literal width="1"/>
									<field value="property" width="10"/>
									<literal width="1"/>
									<field value="age" width="6" align="'right'"/>
									<literal width="1"/>
									<field value="adult ? 'yes' : 'no'" width="5" align="'center'"/>
								</Line>
							</Output>
						</FieldDetails>

						<FieldFooter>
							<Output>
								<HorizontalLine size="1" color="'black'"/>
								<Line>
									<literal>Detail footer row 1</literal>
								</Line>
								<Line>
									<literal>Detail footer row 2</literal>
								</Line>
								<HorizontalLine size="1" color="'black'"/>
							</Output>
						</FieldFooter>
					</Detail>
				</Report>
			</pd>
		</pr>
	</Part>
</OpenCReport>

=== zboszor/OpenCReports/examples/example2/example2.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
    <Report query="q">
        <PageHeader>
            <Output>
                <Line>
                    <literal width="20">The Flintstones</literal>
                    <field value="printf('Page %d / %d', r.pageno, r.totpages)" align="right" />
                </Line>
            </Output>
        </PageHeader>

        <PageFooter>
            <Output>
                <Line>
                    <literal>The Flintstones</literal>
                    <field value="printf('Page %d / %d', r.pageno, r.totpages)" align="right" />
                </Line>
            </Output>
        </PageFooter>

        <Detail>
            <FieldHeaders>
                <Output>
                    <Line>
                        <literal width="4" align="'right'">ID</literal>
                        <literal width="1"/>
                        <literal width="20">Name</literal>
                        <literal width="1"/>
                        <literal width="8" align="'center'">Property</literal>
                        <literal width="1"/>
                        <literal width="6">Age</literal>
                        <literal width="1"/>
                        <literal width="5" align="'center'">Adult</literal>
                    </Line>
                </Output>
            </FieldHeaders>

            <FieldDetails>
                <Output>
                    <Line>
                        <field width="4" align="right" value="id" />
                        <literal width="1"/>
                        <field width="20" value="name" />
                        <literal width="1"/>
                        <field width="8" align="'center'" value="property" />
                        <literal width="1"/>
                        <field width="6" align="'right'" value="age" format="'%.2d'" />
                        <literal width="1"/>
                        <field value="adult ? 'yes' : 'no'" width="5" align="'center'"/>
                    </Line>
                </Output>
            </FieldDetails>
        </Detail>
    </Report>
</OpenCReport>

=== zboszor/OpenCReports/tests/layout_xml24_test.xml
<?xml version="1.0"?>
<!DOCTYPE OpenCReport SYSTEM "opencreport.dtd">
<OpenCReport>
	<Datasources>
		<Datasource name="myarray" type="'array'" />
	</Datasources>
	<Queries>
		<Query name="a" datasource="myarray" value="'array'" coltypes="'coltypes'" rows="0" cols="5" />
	</Queries>
	<Report fontSize="12">
		<NoData>
			<Output>
				<HorizontalLine size="1" color="'Black'" />
				<Line>
					<field value="'OpenCReports has links now!'" link="'https://github.com/zboszor/OpenCReports'" />
				</Line>
				<HorizontalLine size="1" color="'Black'" />
				<Line>
					<literal link="'https://github.com/zboszor/OpenCReports'" >OpenCReports has links now!</literal>
				</Line>
				<HorizontalLine size="1" color="'Black'" />
			</Output>
		</NoData>
	</Report>
</OpenCReport>
